package com.swidch.otacauth.Utils.sharedPreference

object SharedPreferenceHelper {
    const val PREFERENCE = "SWIDCH_PLC_AUTH_PREF"

    const val KEY_STRING_REGIST_QR = "KEY_STRING_REGIST_QR"
    const val KEY_STRING_ACCOUNT_LIST = "KEY_STRING_ACCOUNT_LIST "
    const val KEY_STRING_CHANGE_ACCOUNT_LIST = "KEY_STRING_CHANGE_ACCOUNT_LIST "
    const val KEY_STRING_PIN_PASSWORD = "KEY_STRING_PIN_PASSWORD"
    const val KEY_STRING_SECURITY_STATUS = "KEY_STRING_SECURITY_STATUS"
    const val KEY_STRING_AUTH_STATUS = "KEY_STRING_AUTH_STATUS"

}